CREATE TABLE Back
(
BackID INTEGER IDENTITY (1,1) CONSTRAINT PK1 PRIMARY KEY (BackID),
Back DATE,
Tax DECIMAL(10,2),
BackSum DECIMAL(10,2),
Seller VARCHAR(15)
)
CREATE TABLE Client
(
ClientID INTEGER IDENTITY (1,1) CONSTRAINT PK2 PRIMARY KEY (ClientID),
BackID INT CONSTRAINT FK1 FOREIGN KEY (BackID) REFERENCES Back (BackID),
Surname VARCHAR(50),
Names VARCHAR(40),
Patronymic VARCHAR(50),
Dates DATE,
Addres VARCHAR(60),
Phone VARCHAR(15),
Passport VARCHAR(20),
PassportDate DATE,
Region VARCHAR(40)
)
CREATE TABLE Registrar
(
RegistrarID INTEGER IDENTITY (1,1) CONSTRAINT PK3 PRIMARY KEY (RegistrarID),
Surname VARCHAR(50),
Names VARCHAR(50),
Patronymic VARCHAR(50)
)
CREATE TABLE Category
(
CategoryID INTEGER IDENTITY (1,1) CONSTRAINT PK4 PRIMARY KEY (CategoryID),
Category VARCHAR(15)
)
CREATE TABLE Sale
(
SaleID INTEGER IDENTITY (1,1) CONSTRAINT PK5 PRIMARY KEY (SaleID),
FreeThing float (4),
Price DECIMAL(10,2)
)
CREATE TABLE Thing
(
ThingID INTEGER IDENTITY (1,1) CONSTRAINT PK6 PRIMARY KEY (ThingID),
CategoryID INT CONSTRAINT FK2 FOREIGN KEY (CategoryID) REFERENCES Category (CategoryID),
SaleID INT CONSTRAINT FK3 FOREIGN KEY (SaleID) REFERENCES Sale (SaleID),
Thing VARCHAR(30),
Counts float (2),
Defects BIT,
Cost DECIMAL(10,2),
Summ DECIMAL(10,2),
Comment TEXT
)
CREATE TABLE Agreement
(
AgreementID INTEGER IDENTITY (1,1) CONSTRAINT PK7 PRIMARY KEY (AgreementID),
ClientID INT CONSTRAINT FK4 FOREIGN KEY (ClientID) REFERENCES Client (ClientID),
ThingID INT CONSTRAINT FK5 FOREIGN KEY (ThingID) REFERENCES Thing (ThingID),
RegistrarID INT CONSTRAINT FK6 FOREIGN KEY (RegistrarID) REFERENCES Registrar (RegistrarID),
StartDate DATE,
PercentDate DATE,
StopDate DATE
)